Repository checkstyle/checkstyle, pull requests merged in 2022-04, with the labels that each got.

#11497 config: bump hibernate search to jdk 17
  .ci/jsoref-spellchecker/whitelist.words
  .ci/travis.sh
  .travis.yml
Labels: discussion ongoing

#11544 minor: remove testLocaleIsSupported tests
  src/test/java/com/puppycrawl/tools/checkstyle/DefaultLoggerTest.java
  src/test/java/com/puppycrawl/tools/checkstyle/api/ViolationTest.java
Labels: miscellaneous

#11322 Issue #11214: Specified violation message in EmptyBlockCheck
  src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
  src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock/InputEmptyBlockSwitchExpressions.java
  src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock/InputEmptyBlockCase.java
  src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock/InputEmptyBlockCase2.java
  src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock/InputEmptyBlockDefault.java
  src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock/InputEmptyBlockDefault2.java
  src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock/InputEmptyBlockSemantic.java
  src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock/InputEmptyBlockSemantic2Statement.java
  src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock/InputEmptyBlockSemantic2Text.java
  src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock/InputEmptyBlockSemanticStatement.java
  src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock/InputEmptyBlockSemanticText.java
Labels: awaiting changes
