Repository checkstyle/checkstyle, pull requests merged in 2022-11, with the labels that each got.

#11644 Issue #11604: allow 3rd party Check providers to group modules under custom parent module
  .ci/pitest-suppressions/pitest-utils-suppressions.xml
  config/archunit-store/slices_should_be_free_of_cycles_suppressions
  src/main/java/com/puppycrawl/tools/checkstyle/utils/ModuleReflectionUtil.java
  src/test/java/com/puppycrawl/tools/checkstyle/PackageObjectFactoryTest.java
  src/test/java/com/puppycrawl/tools/checkstyle/internal/ArchUnitSuperClassTest.java
  src/test/java/com/puppycrawl/tools/checkstyle/internal/ImmutabilityTest.java
  src/test/java/com/puppycrawl/tools/checkstyle/utils/ModuleReflectionUtilTest.java
Labels: approved, new feature

#12421 infra: move release note generation to github action
  .github/workflows/releasenotes-gen.yml
  README.md
Labels: miscellaneous

#11617 Issue #11604: separates detail ast from xpath
  .ci/checker-framework-suppressions/checker-nullness-optional-interning-suppressions.xml
  .ci/pitest-suppressions/pitest-xpath-suppressions.xml
  config/archunit-store/slices_should_be_free_of_cycles_suppressions
  config/import-control.xml
  config/pmd.xml
  src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MatchXpathCheck.java
  src/main/java/com/puppycrawl/tools/checkstyle/gui/TreeTable.java
  src/main/java/com/puppycrawl/tools/checkstyle/utils/XpathUtil.java
  src/main/java/com/puppycrawl/tools/checkstyle/xpath/AbstractElementNode.java
  src/main/java/com/puppycrawl/tools/checkstyle/xpath/AbstractNode.java
  src/main/java/com/puppycrawl/tools/checkstyle/xpath/AbstractRootNode.java
  src/main/java/com/puppycrawl/tools/checkstyle/xpath/AttributeNode.java
  src/main/java/com/puppycrawl/tools/checkstyle/xpath/ElementNode.java
  src/main/java/com/puppycrawl/tools/checkstyle/xpath/RootNode.java
  src/test/java/com/puppycrawl/tools/checkstyle/xpath/XpathMapperTest.java
Labels: approved, miscellaneous
