Repository checkstyle/checkstyle, pull requests merged in 2024-10, with the labels that each got.

#15771 Issue #15769: added suppression for separate code blocks and updated documentation
  .ci/google-java-format.sh
  src/it/java/com/google/checkstyle/test/chapter4formatting/rule42blockindentation/BlockIndentation2SpacesTest.java
  src/it/resources/com/google/checkstyle/test/chapter4formatting/rule42blockindentation/InputFormattedIndentationCodeBlocks.java
  src/it/resources/com/google/checkstyle/test/chapter4formatting/rule42blockindentation/InputIndentationCodeBlocks.java
  src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4822declaredwhenneeded/InputDeclaredWhenNeeded.java
  src/main/resources/google_checks.xml
  src/xdocs/google_style.xml
Labels: hacktoberfest-accepted

#14954 Pull #14954: Add upwards compat for deprecated classes in maven-check…
  config/linkcheck-suppressions.txt
  src/main/java/com/puppycrawl/tools/checkstyle/SarifLogger.java
  src/test/java/com/puppycrawl/tools/checkstyle/SarifLoggerTest.java
Labels: discussion ongoing

#15687 JavadocMethodCheck: removed unnecessary tokens from acceptable
  src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java
  src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheckTest.java
  src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodRecordsAndCompactCtors.java
Labels: breaking compatibility
