Repository checkstyle/checkstyle, pull requests merged in 2024-11, with the labels that each got.

#14514 doc: improve CONTRIBUTING.md
  .github/CONTRIBUTING.md
  .github/GSOC.md
  README.md
  config/jsoref-spellchecker/whitelist.words
  src/xdocs/contributing.xml
Labels: awaiting changes

#14882 Issue #14573: fix javadoc type check for empty tags
  src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTypeCheck.java
  src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/utils/BlockTagUtil.java
  src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTypeCheckTest.java
  src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/utils/BlockTagUtilTest.java
  src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctype/InputJavadocTypeBadTag.java
  src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctype/InputJavadocTypeTypeParamsTags_1.java
  src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctype/InputJavadocTypeUnusedParamInJavadocForClass.java
Labels: abandoned, awaiting response

#14803 Issue #13061: Update grammar for @exception, @throws, and @param tags
  src/main/resources/com/puppycrawl/tools/checkstyle/grammar/javadoc/JavadocParser.g4
  src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/NonEmptyAtclauseDescriptionCheckTest.java
  src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/nonemptyatclausedescription/InputNonEmptyAtclauseDescriptionTwo.java
Labels: abandoned, awaiting response

#15937 Pull #15937: avoid reliance on `File.createTempFile` implementation d…
  src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/XdocGenerator.java
Labels: miscellaneous
